services:
  flutter-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamoney-dev
    environment:
      - FLUTTER_HOME=/usr/local/flutter
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    user: flutteruser
    networks:
      - mamoney-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5037:5037"
      - "8081:8080"

networks:
  mamoney-network:
    driver: bridge
